### ISSUE TITLE
Contributing.md Needs a correction

### ISSUE THREAD

**Issue by prakhar728** [DSC-IIIT-Surat/DevQueryResolver#2]
It needs clear instructions on how to setup the local environment to properly contribute without conflictong with the main branch of the main Repository.

Secondly the setting up of the ENV file lacks one field, in the **[Contributing.md](https://github.com/DSC-IIIT-Surat/DevQueryResolver/blob/main/CONTRIBUTING.md)** . MONGO_USER. I'd like to fix that.

**Comment by AvanishCodes** [comment]
> It needs clear instructions on how to setup the local environment to properly contribute without conflictong with the main branch of the main Repository.
> 
> Secondly the setting up of the ENV file lacks one field, in the **[Contributing.md](https://github.com/DSC-IIIT-Surat/DevQueryResolver/blob/main/CONTRIBUTING.md)** . MONGO_USER. I'd like to fix that.

Yes, there is some little issue in the file.
You can create a PR for the same.

**Comment by AvanishCodes** [comment]
Closed in #3
